apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-binding
roleRef:
  kind: ClusterRole
  name: fluent-bit
  apiGroup: rbac.autorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluent-bit-sa
    namespace: efk