apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: efk
spec:
  selector:
    app: kibana
  type: NodePort
  ports:
    - targetPort: 5601
      port: 5601
      nodePort: 30601
      protocol: TCP
