apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: default
spec:
  selector:
    app: python
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30005
      protocol: TCP
