apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mongo
  template:
    metadata:
      labels:
        db: mongo
    spec:
      containers:
        - name: mongo-container
          image: mongo:6.0.25
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: db-volume
              mountPath: /data/db
      volumes:
        - name: db-volume
          hostPath:
            - path: /data